name: Unity Runner
author: PhantasmicDev
description: Run command line arguments in Unity during your GitHub workfow.

inputs:
  version:
    description: The version of Unity to install, if empty, the ProjectSettings/ProjectVersion.txt is used and if no ProjectVersion.txt file is present, the latest stable version will be used.
    required: false
  command:
    description: The command line argument to run in Unity.

runs:
  using: node16
  main: dist/index.js