name: Test Action

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Run Action
        uses: ./
        with:
          version: ${{ inputs.version}}
          command: -createProject "${{ github.workspace}}/MyProject"
        env:
          UNITY_USERNAME: ${{ secrets.UNITY_USERNAME }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
